-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keepclasseswithmembers class kotlinx.serialization.json.** { kotlinx.serialization.KSerializer serializer(...); }
-keep,includedescriptorclasses class com.bmscompanion.app.**$$serializer { *; }
-keepclassmembers class com.bmscompanion.app.** { *** Companion; }
-keepclasseswithmembers class com.bmscompanion.app.** { kotlinx.serialization.KSerializer serializer(...); }
